### ISSUE TITLE
Idle Chatter is active during cutscenes

### ISSUE THREAD

**Issue by TheWonderFromDownUnder** [michael-fadely/sadx-idle-chatter#3]
Pressing the idle chatter button will make the animation play even during cutscenes.

![64194725-c69b3000-ce77-11e9-9814-5746dc3d34d1](https://user-images.githubusercontent.com/52037295/64219359-1819de00-cebd-11e9-8036-175aaa84d3e6.png)

Note: Only works during points where they stand still, and does not play the idle voices, only the animation.

**Comment by michael-fadely** [comment]
...can I consider this a feature?

Thanks for the report!
